### ISSUE TITLE
memory leak in got@11

### ISSUE THREAD

**Issue by Kikobeats** [jaredwray/cacheable#233]
**Describe the bug**

`got@11` is still very used, and it depends on `cacheable-request@7.0.2`. There is a bug resolved recently that is still present in that cacheable-request version:

https://github.com/jaredwray/cacheable-request/releases/tag/v10.2.6

**How To Reproduce (best to provide workable code or tests!)**

The following commit should be ported in order to address the issue of the v7 tag version:

https://github.com/jaredwray/cacheable-request/compare/main...Kikobeats:cacheable-request:buggy

Also, the changes include the use of an optional operator for accessing cache event emitter methods; In that way, it's possible to avoid the issue if the cache provided that doesn't extend from EventEmitter (so there is no event to attach neither remove)

I can't promote a PR here since the only branch is main. Could you please integrate this changes and release `cacheable-request@7.0.3`? 🙂

**Comment by jaredwray** [comment]
@Kikobeats - thanks for the note and we do have a commonjs branch but it is later in the release. 

Do you want to create a new one and I can look at doing a release as 7.0.3? 

Let me know if you want to chat about how to do this best.

**Comment by Kikobeats** [comment]
done!

**Comment by jaredwray** [comment]
I am wondering if we need to pull the code from v7 and create that as a branch as the current one is too new still and after testing there seems to be a ton of changes. 

What if I created a branch that is just based on https://github.com/jaredwray/cacheable-request/releases/tag/v7.0.2 then you do a pull request against that with these changes?

**Comment by Kikobeats** [comment]
Hello,

is this the code change? https://github.com/jaredwray/cacheable-request/commit/c09f1cd5eb219e029ef9d01eddefed3670b0643e

The code looks good to me. It could better if a test unit is added.

**Comment by jaredwray** [comment]
Thanks. Do you want to add a unit test to the v7 branch to validate? Also, how can we test that this version of `cacheable-request` works well with `got@11`? Is there a place to validate it well or a scenario where you are seeing the memory leak?

**Comment by jaredwray** [comment]
@Kikobeats - have you been able to validate this code change?

**Comment by Kikobeats** [comment]
Sorry for the delay. The scenario is [api.microlink.io](https://api.microlink.io), the endpoint is handling +50M requests per month, so it's very sensitive to little bugs like this. 

Unfortunately, I don't have the time for writing the test – If you ship v7.0.3 I can test it on production servers and tell you 🙂

**Comment by otaviosilva22** [comment]
@jaredwray this version 7.0.3 broked new deploys em node version < 14. Please, check this issue: https://github.com/jaredwray/cacheable-request/issues/246

**Comment by jaredwray** [comment]
Thanks. the new release `v7.0.4` should have resolved as it is based on 7.0.2.

**Comment by jaredwray** [comment]
@Kikobeats - I rolled this back and did some changes on it for `v7.0.5-beta.0` as it caused multiple issues. You can test this out by referencing the following github path. 

```
https://github.com/jaredwray/cacheable-request/tree/v7
```

To do this in your npm package do the following:
```json
// in your package.json
"dependencies": {
"cacheable-request": "jaredwray/cacheable-request#v7",
}

```

**Comment by jaredwray** [comment]
closing on no response
