### ISSUE TITLE
Cache Manager - Migrate to using Keyv

### ISSUE THREAD

**Issue by Davrosh** [jaredwray/cacheable#766]
**Is your feature request related to a problem? Please describe.**

The `ttl` function inside `cache-manager-redis-yet` does not appear to support the `keyPrefix` feature.
The `keyPrefix` option is not available on the type definition when initializing `redisClusterStore` or `redisClusterInsStore` even though it seems like it should be supported in the same way as the non-cluster versions.

Ideally, group operations like `keys(pattern)` or `reset()` should also support the `keyPrefix` under the hood. I'm not sure if this view is shared by everyone.

**Describe the solution you'd like**

For `cache-manager-redis-yet`:
Add support for `keyPrefix` in `ttl` inside `cache-manager-redis-yet`
Add support for `keyPrefix` in type definition of options for `redisClusterStore` and `redisClusterInsStore`, i.e., `CustomOptions`.
Ideally, add support for `keyPrefix` in `keys` or `reset` for both the regular client and the cluster versions.

I have added a PR (#765) to add `keyPrefix` support for `ttl`, add `CustomOptions` to `redisClusterStore` and `redisClusterInsStore` options, and add tests that cover the above.
I've also readded existing tests for cluster (and added a `redis-cluster` deployment in the `docker-compose.yaml` file for those tests to run on). In those tests I've added curly braces around a few of the keys, e.g., '{foo}2' in order to avoid CROSSSLOT errors common when using commands such as `mget` in cluster mode.
During testing, I also found that `keyPrefix` is not supported by `mget` and `mdel` and added tests that cover those cases as well.
I personally would have also liked to add `keyPrefix` support for `keys` and `reset` in both the regular and cluster stores, but felt it might not be the behavior expected by all users of this library. @jaredwray Please let me know your thoughts on this, and I will also add support for this.

**Comment by jaredwray** [comment]
@Davrosh - thanks so much for doing this. I am reviewing it and it might take a couple of days as this is a legacy code base that I am not planning to support long term. 

Our plan is to move to using all [Keyv](https://keyv.org) storage adapters and will be deprecating the redis and ioredis storage adapters by end of year. 

I think the Keyv would solve your issue as it already has namespace support. Correct?

**Comment by Davrosh** [comment]
@jaredwray Thanks for replying!
Regarding Keyv, I think so - at least from the few minutes I've spent reading about it (it would be nice if it supported the same options as the redis client/cluster client like your functions do but I don't think that is the case).
My use case involves the standard `get`, `del` and `ttl` with the redisClusterStore as well as `keys(pattern)` and to an extent `reset()` during testing.

So I actually don't mind so much about the PR approval getting delayed if I can get around the `ttl` not being supported and the type definitions for now. Please also let me know if you think such a long PR is too much for a codebase you plan on deprecating anyway, and If I should submit a smaller PR with just those few changes and the few necessary tests.

I think regarding implementing `keyPrefix` for `keys` that it's less unintuitive as I had thought, mainly because `keys` is a command that's usually advised against being run in production, so I guess it's safe to add support for `keyPrefix` on it.
The command `reset` is probably also such a command but I'm currently debating how it can be substituted by a "flush by prefix" command efficiently.

**Comment by Davrosh** [comment]
@jaredwray For my case, not sure but I might also have to wait until your new major version is supported by [github.com/nestjs/cache-manager](https://github.com/nestjs/cache-manager) unless it will be compatible with `cache-manager` even after the rewrite.
If in the meantime you can also add `keyPrefix` `ttl` support and add the `CustomOptions` to `redisClusterStore`, I'd be grateful. 🙏

**Comment by jaredwray** [comment]
Yep. Might be a bit for all of those features as realistically we will need @keyv/redis to be upgraded also to do all of that.

**Comment by jaredwray** [comment]
https://github.com/jaredwray/cacheable/pull/792

This will be a breaking change which is why we are moving to `v6.0.0` A couple of features will be added in:

- [ ] Added in support for Keyv thanks to @timphandev 🎉 
- [ ] Emits via `Hookified`
- [ ] An adapter `KeyvAdapter` which is used to convert `cache-manager` adapters to `Keyv`

## Breaking Changes

With this major change we will be removing `caching` and a primary with `createCache` as:

```js
// Single store
const cache = createCache({
  stores: [new Keyv()],
})

// Multiple stores
const cache = createCache({
  stores: [
    // Redis store
    new Keyv({
      store: new KeyvRedis('redis://user:pass@localhost:6379'),
    }),

    // Sqlite store
    new Keyv({
      store: new KeyvSqlite('cache.db'),
    }),
  ],
})
``` 

## KeyvAdapter

We built in a KeyvAdapter to `cache-manager` for easier migration and you can use it like the followiing:

```js
import { KeyvAdapter, createCache} from `cache-manager`;
import { redisStore } from 'cache-manager-redis';

const keyv = new KeyvAdapter(redisStore);
const cache = createCache({ stores: [ keyv ] })
```

**Comment by jaredwray** [comment]
cache-manager v6 has been released
