### ISSUE TITLE
Granular caching of functions based on their arguments - `cache-manager-function`

### ISSUE THREAD

**Issue by tomerh2001** [jaredwray/cacheable#767]
Hi, just sharing this library I created: https://github.com/tomerh2001/cache-manager-function

It allows for granular caching of functions based on their arguments and supports decorators.

If you have a list of community-made libraries, you can feel free to include it

**Comment by jaredwray** [comment]
@tomerh2001 - thanks for posting this. I am including this now in the readme!

**Comment by jaredwray** [comment]
Will be pushed live on the next release. You can see it here: https://github.com/jaredwray/cacheable/blob/main/packages/cache-manager/README.md#community-additions
