### ISSUE TITLE
The recent change in the storage format of cache-manager-ioredis-yet may cause inconsistent behavior across different versions.

### ISSUE THREAD

**Issue by turastory** [jaredwray/cacheable#769]
**Describe the bug**
See this commit: https://github.com/jaredwray/cacheable/commit/9647acf6669d1cf3ac6b446a70fbc6babddf50bc

In case of storing data in previous version of cache manager and retrieving data in newer version, the storage format is different and you get the wrong result.

This change might break the apps that uses this dependency and should be treated as a breaking change.

**I suggest to revert this change.** I don't know why there's `v` in the first place, but that's how it is right now, so we need to keep it. Especially if you're planning to deprecate it in a couple of months.

I'll stick to the older version for now.

**How To Reproduce (best to provide workable code or tests!)**
1. Install 2.0.3 version of `cache-manager-ioredis-yet`
2. Store a value using `cacheManager.set()`
3. Upgrade to 2.1.1
4. Retrieve a value using `cacheManager.get()`

It gives you a value in this format: `{"v": <value>}`.

---

If you don't mind, I'll create a new pull request for it.

**Comment by jaredwray** [comment]
@turastory thanks so much for the detailed bug report before you do the pool request. One thing I do want to let you know is that we will be switching over to using the keyv storage adapters in the near future, which might solve that issue completely.

**Comment by jaredwray** [comment]
Going to close this out and focus on this: https://github.com/jaredwray/cacheable/issues/766
