### ISSUE TITLE
ttlAutopurge is missing in v6.0.0.

### ISSUE THREAD

**Issue by fanksy** [jaredwray/cacheable#793]
ttlAutopurge is very useful on computers with limited memory.

Could this parameter be added back?

**Comment by jaredwray** [comment]
Hi @fanksy 👋  - thanks for the request and we decided not to have this as Keyv can do this via `lru-cache` or `CacheableMemory` (preferred). Here are examples of enabling `CacheableMemory` with lru:

```js
import {createCache} from 'cache-manager';
import {Keyv} from `keyv`;
import {CacheableMemory} from 'cacheable';

const keyv = new Keyv({ store: new CacheableMemory({ttl: 6000, lruSize: 1000}));
const cache = createCache({ stores: [keyv] });
```

In this example we set the ttl to expire in 5 minutes and also to keep the cache to 1000 items. Have fun!
