### ISSUE TITLE
CommonJS support is gone with 6.0.0

### ISSUE THREAD

**Issue by nicokaiser** [jaredwray/cacheable#794]
While being not very amused about yet again another breaking change I tried to migrate a project to cache-manager v6.0.0.

The cacheable README states that it has "ESM and CommonJS support", but this seems not true, since `hookified` seems to fail with CJS:

```js
const { CacheableMemory } = require('cacheable');
```

```
/Users/nkaiser/src/test/node_modules/cacheable/dist/index.cjs:31
var import_hookified = require("hookified");
                       ^
Uncaught:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/nkaiser/src/test/node_modules/hookified/dist/index.js from /Users/nkaiser/src/test/node_modules/cacheable/dist/index.cjs not supported.
Instead change the require of index.js in /Users/nkaiser/src/test/node_modules/cacheable/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/nkaiser/src/test/node_modules/cacheable/dist/index.cjs:31:24) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by nicokaiser** [comment]
See jaredwray/hookified#9

**Comment by jaredwray** [comment]
@nicokaiser  - thanks for the update as we thought `emittery` was compatible. We are working on a fix and should have it out in the next day or so.

**Comment by jaredwray** [comment]
@nicokaiser - also, I understand your frustration but wanted to let you know that now that we are on Keyv we will be making this more stable moving forward. The previous code base was not maintainable with the legacy storage adapters.

**Comment by jaredwray** [comment]
`cacheable@1.3.0` should do the trick. Please note that while we are attempting to support CJS it is getting harder to do that and over the next year or so moving to ESM is the future.

**Comment by nicokaiser** [comment]
Awesome, thank you very much for fixing this!
