### ISSUE TITLE
No Changelog or Migration guide for v6?

### ISSUE THREAD

**Issue by TotallyNotYT** [jaredwray/cacheable#805]
As there's no changelog  or migration guide I'm going to have to assume that the v6 release is not final yet and will still be worked on. This is of course a bit surprising due to the fact that the new version is already on NPM, but I cannot implement this upgrade into my repository without the knowledge to where multiple types we use (e.g. `import { Cache } from 'cache-manager';`) have gone. I would love to get a response as soon as possible, thanks in advance

**Comment by jaredwray** [comment]
@TotallyNotYT - this is live and already being used but you are correct that this is a full rewrite to the previous version as we have moved to the primary store backend by [Keyv](https://keyv.org). Most of the functions have remained the same but there are some changes. To migrate you can look at this quick start and full documentation: https://github.com/jaredwray/cacheable/blob/main/packages/cache-manager/README.md#quick-start

If you are looking just how to import and get up and running based on what was there before `import { Cache } from 'cache-manager';`

```js
import { Keyv } from 'keyv';
import { createCache } from 'cache-manager';

// Memory store by default
const cache = createCache()

// Single store which is in memory
const cache = createCache({
  stores: [new Keyv()],
})
```
