### ISSUE TITLE
Help understanding setup

### ISSUE THREAD

**Issue by RWOverdijk** [jaredwray/cacheable#835]
I followed the example:

```ts
import { Keyv } from 'keyv';
import { KeyvRedis } from '@keyv/redis';
import { CacheableMemory } from 'cacheable';
import { createCache } from 'cache-manager';

// Multiple stores
const cache = createCache({
  stores: [
    //  High performance in-memory cache with LRU and TTL
    new Keyv({
      store: new CacheableMemory({ ttl: 60000, lruSize: 5000 }),
    }),

    //  Redis Store
    new Keyv({
      store: new KeyvRedis('redis://user:pass@localhost:6379'),
    }),
  ],
})
```

And installed all listed dependencies, but I am getting a typescript error:

<img width="702" alt="image" src="https://github.com/user-attachments/assets/59ad98a3-831d-43d7-9c79-7a316ee1aff6">

It's not clear to me what is going on or what I should be doing.

EDIT:

I get the same regardless of which store I use (either the memory one, or the redis one, or both)

EDIT 2:

Installed versions:

- @keyv/redis: 3.0.1
- cache-manager 5.7.6
- keyv 5.1.0
- cacheable 1.8.0

**Comment by jaredwray** [comment]
@RWOverdijk - thanks so much for bringing this to my attention as `KeyvRedis` is a default export which is where it is erroring. I am updating the documentation as it is a bit off but this will work:

```typescript
import { Keyv } from 'keyv';
import KeyvRedis from '@keyv/redis';
import { CacheableMemory } from 'cacheable';
import { createCache } from 'cache-manager';

// Multiple stores
const cache = createCache({
  stores: [
    //  High performance in-memory cache with LRU and TTL
    new Keyv({
      store: new CacheableMemory({ ttl: 60000, lruSize: 5000 }),
    }),

    //  Redis Store
    new Keyv({
      store: new KeyvRedis('redis://user:pass@localhost:6379'),
    }),
  ],
})
```

Also, there was an update with `CacheableMemory` that it now exports a native Keyv storage adapter and you can use it like this:

```typescript
import { Keyv } from 'keyv';
import KeyvRedis from '@keyv/redis';
import { KeyvCacheableMemory } from 'cacheable';
import { createCache } from 'cache-manager';

// Multiple stores
const cache = createCache({
	stores: [
		//  High performance in-memory cache with LRU and TTL
		new Keyv({
			store: new KeyvCacheableMemory({ttl: 60_000, lruSize: 5000}),
		}),

		//  Redis Store
		new Keyv({
			store: new KeyvRedis('redis://localhost:6379'),
		}),
	],
});
```

Here is an example: https://github.com/jaredwray/cacheable/blob/ac75462e12ec7abd0647eb5654ae9364964f787b/packages/cache-manager/test/example.test.ts#L7

**Comment by RWOverdijk** [comment]
@jaredwray thanks, but this gives me the same issue. It's saying the issue is with stores in createCache.

**Comment by jaredwray** [comment]
Cacheable will be enabling name spaces in the future. Think of cacheable as the next generation caching library as cache-manager is our previous. Also, if you want to do name space support you can just use Keyv (without the lru) by doing 

```javascript
import { createCache } from 'cache-manager';
import { KeyvCacheableMemory } from 'cacheable';
import { Keyv } from 'keyv';
import KeyvRedis from '@keyv/redis';

// Multiple stores
const cache = createCache({
  stores: [
    //  High performance in-memory cache with LRU and TTL
    new Keyv({
      store: new Keyv(),
    }),

    //  Redis Store
    new Keyv({
      store: new KeyvRedis('redis://localhost:6379'),
    }),
  ],
});
```

I am able to get this to work in this example: https://github.com/jaredwray/cacheable/blob/main/packages/cache-manager/test/example.test.ts

**Comment by RWOverdijk** [comment]
I'll try that. I just need regular memory cache anyway so that might be perfect for now. Then I can just use keyv and I won't need anything else 😄. Thanks!

**Comment by RWOverdijk** [comment]
@jaredwray That too does not seem to work for me? I get:

> TypeError: Cannot read properties of undefined (reading 'includes')
>    at node_modules/keyv/dist/index.cjs:295:131

Which is this line:

```js
return iterableAdapters.includes(this.opts.store.opts.dialect) || iterableAdapters.some((element) => this.opts.store.opts.url.includes(element));
```

My code:

```ts
new Keyv(
        {
          store: new Keyv(),
        },
        { namespace },
      );
```

This does seem to work:

```ts
new Keyv(null, { namespace })
```

Does that achieve the same thing?

**Comment by jaredwray** [comment]
The correct pattern should passing in just the namespace:

```javascript

const namespace = 'namespace1';
const keyv = new Keyv({ namespace });

```

This will do an in-memory `Map()` by default and set the namespace. If you want to set the store you can do that by doing anything that is `Map()` related like `quick-lru` or any `KeyvStorageAdapter` such as `@keyv/redis`. Here is an example with `@keyv/redis`.

```
import KeyvRedis from '@keyv/redis';
import Keyv from 'keyv';

const store = new KeyvRedis('redis://user:pass@localhost:6379');
const namespace = 'namespace1';
const keyv = new Keyv({ store, namespace});
```
