### ISSUE TITLE
Date objects are stored as strings

### ISSUE THREAD

**Issue by lugrinder** [jaredwray/cacheable#843]
**Describe the bug**
Date properties are stored as string instead of object. 
On many ORM, date/time fields are returned as Date objects, so cache its results causes this issue.
I think that versions before `keyv` works, but not really sure, I've detected the issue after updating to v6.
If this will be the default behavior, please fix the documentation and add typescript type guard to ensure that only valid values can be cached, or better, transform the result type for `wrap` for all Date properties to be the original returned value (Date) and string: Date | string.

**How To Reproduce (best to provide workable code or tests!)**
Cache any value with a Date property.

**Comment by lugrinder** [comment]
I can confirm that v5 stores Date as object and don't have this issue. I've fixed it, adding the next typescript type to the returned value of `wrap` that have `Date` properties, so typescript warns about this if I've tried to use as `Date`:

```typescript
type StringifyObject<T> = {
    [P in keyof T]: Extract<T[P], object> extends never ? T[P] : T[P] | string
}
```

At least, add something similar to the returned `wrap` value.

**Comment by jaredwray** [comment]
@lugrinder - thanks for letting us know. Can you tell me what package you are seeing this on? Is this `cache-manager`?

Also, can you give me an example of where you are using this code to fix it?

**Comment by lugrinder** [comment]
Yes, `cache-manager`.
You can see here a [running example](https://codesandbox.io/p/devbox/amazing-wildflower-zyjl6j).

**Comment by jaredwray** [comment]
got it. I see. Where are you adding this code to fix it?

```
type StringifyObject<T> = {
    [P in keyof T]: Extract<T[P], object> extends never ? T[P] : T[P] | string
}
```

**Comment by lugrinder** [comment]
I'm not modified the original code, I've done something like this:

```typescript
async function getData(name: string) {
    const result = await cache.wrap(name, async () => {
        return new Promise((resolve) => {
            resolve({
                a: 'hello',
                b: new Date
            })
        })
    })
    return result as StringifyObject<typeof result>
}
```
If you do it inside `wrap`, there is no need to add in all calls to `wrap`, you can infer from the wrapped promise.
The question is, if not possible to store objects as v5, at least make a union for the transformed types and ensure that typescript will warn if you don't take care.

**Comment by jaredwray** [comment]
@lugrinder - thanks for the info and I am going to see what we can do to help with this.

**Comment by jaredwray** [comment]
@lugrinder - just another thought is that you can set Keyv with another parser that handles `Date` better such as `superjson`. Here is an example of how to do that:

```javascript
import Keyv from 'keyv';
import superjson from 'superjson'
import {createCache} from 'cache-manager';

const keyv = new Keyv({ serialize: superjson.stringify, deserialize: superjson.parse });
const cache = createCache({ stores: [keyv] });

```

**Comment by jaredwray** [comment]
@lugrinder - looks like the best way is to do the parsing option. Will write more on this a bit later but going to close this. Let me know if you need any other help.

**Comment by jaredwray** [comment]
Hi @andreialecu - thanks and we have seen multiple people that are using in memory struggle with this. We are thinking that an enhancement we are planning is to make it so that if you do something simple like `createCache()` it will remove the serialization for you by default. Here is an example on how to bypass this:

```js
import { createCache } from "cache-manager";
import { Keyv } from "keyv";

const keyv = new Keyv();
keyv.serialize = undefined;
keyv.deserialize = undefined;

const memoryCache = createCache({
	stores: [keyv],
});
```

if you want to use `CacheableMemory` there is a helper function to create the Keyv instance and it removes serialization:

```js
import { createCache } from "cache-manager";
import { createKeyv } from "cacheable";

const keyv = createKeyv(); // This creates a Keyv instance with CacheableMemory

const memoryCache = createCache({
	stores: [keyv],
});

We have also updated the documentation here: https://github.com/jaredwray/cacheable/tree/main/packages/cache-manager#migration-from-v5-to-v6

@andreialecu - in your example you were trying to use `KeyvCacheableMemory` and didnt see serialize or deserialize. That is because it is a `KeyvStorageAdapter` and not a `Keyv` instance.

**Comment by andreialecu** [comment]
We have fixed it by using `superjson` for `serialize` and `deserialize` + redis.

The most pressing issue here is that there should be some indication that this is happening and Dates are turned to strings, as it's very unexpected. I would assume it happens for other things as well.

Perhaps integrating `superjson` by default might be a good idea, otherwise many people will run into this unexpectedly.

Consider this simple case:

`const x = await cache.wrap('test', async () => return new Date(), 1000)`

`x` has a type of `Date` but in practice it will be either a date or a string.

**Comment by lcswillems** [comment]
Hey @jaredwray , encountering the same issue on my side! Very counter intuitive that there is a serialization / deserialization when doing in-memory cache. I'm using cache-manager.

Also your solution @jaredwray doesn't work on my side and it raises TypeScript errors:

![Image](https://github.com/user-attachments/assets/b4e39d88-2d9b-4fba-8b6d-e77173d9a5f5)
