### ISSUE TITLE
New keyPrefix for wrap should be optional

### ISSUE THREAD

**Issue by lugrinder** [jaredwray/cacheable#880]
**Describe the bug**
Any code written with 1.8.1 now raises an error due `options` is mandatory, and shouldn't.
Version 1.8.2 adds `keyPrefix` and `options` to `wrap` function as mandatory, not optional, and should be both optional.

In `wrap` source code, `options` parameter is declared:

```typescript
export type WrapFunctionOptions = {
	ttl?: number | string;
	keyPrefix: string;
};
```

But the use of `keyPrefix` is optional:

```typescript
export function createWrapKey(function_: AnyFunction, arguments_: any[], keyPrefix?: string): string {
	if (!keyPrefix) {
		return `${function_.name}::${hash(arguments_)}`;
	}

	return `${keyPrefix}::${function_.name}::${hash(arguments_)}`;
}
```

So `options` of wrap should be optional, and `keyPrefix` in `WrapFunctionOptions` too.

**Comment by lugrinder** [comment]
Possible simple fix:

```typescript
export type WrapSyncOptions = WrapOptions & {
    cache: CacheableMemory;
};

export type WrapFunctionOptions = Omit<WrapOptions, 'cache'>;

export function wrap<T>(function_: AnyFunction, options?: WrapOptions): AnyFunction {
    const {ttl, keyPrefix, cache} = options || {};

```

This ensures that all `wrap` options are in sync.

**Comment by jaredwray** [comment]
fixing this now. Thanks for looking at it: https://github.com/jaredwray/cacheable/pull/881 release should be out shortly

**Comment by jaredwray** [comment]
@lugrinder - let me know if that worked!

**Comment by lugrinder** [comment]
> @lugrinder - let me know if that worked!

Yes, all right. Thanks...
