### ISSUE TITLE
Trying to understand when to disconnect from the a store like Redis?

### ISSUE THREAD

**Issue by TimothyIp** [jaredwray/cacheable#897]
I can't seem to understand how to disconnect from stores like Redis on app shutdown. What I'm seeing is we are just opening connections via the `KeyvRedis` and nothing about closing the connection.

Is the expectation that we would need to store a separate reference to the redis store and close the connection? Not sure this is mentioned in the docs anywhere.

Taken from the Quick Start examples, if we followed the example, how would we close this redis store connection on app shutdown?
```
import { Keyv } from 'keyv';
import KeyvRedis from '@keyv/redis';
import { CacheableMemory } from 'cacheable';
import { createCache } from 'cache-manager';

// Multiple stores
const cache = createCache({
  stores: [
    //  High performance in-memory cache with LRU and TTL
    new Keyv({
      store: new CacheableMemory({ ttl: 60000, lruSize: 5000 }),
    }),

    //  Redis Store
    new Keyv({
      store: new KeyvRedis('redis://user:pass@localhost:6379'),
    }),
  ],
})

```

**Comment by jaredwray** [comment]
@TimothyIp - you are correct that the current way to do this is to disconnect by going to the stores property `primary or secondary` like so:

```js
import { Keyv } from 'keyv';
import KeyvRedis from '@keyv/redis';
import { CacheableMemory } from 'cacheable';
import { createCache } from 'cache-manager';

// Multiple stores
const cache = createCache({
  stores: [
    //  High performance in-memory cache with LRU and TTL
    new Keyv({
      store: new CacheableMemory({ ttl: 60000, lruSize: 5000 }),
    }),

    //  Redis Store
    new Keyv({
      store: new KeyvRedis('redis://user:pass@localhost:6379'),
    }),
  ],
})

await cache.disconnect();
```

You can see the method in the documentation https://www.npmjs.com/package/cacheable?activeTab=readme#cacheable---api

Let me know if you have any other questions!

**Comment by jaredwray** [comment]
@TimothyIp - so sorry as I didnt realize you were using `cache-manager` and not `cacheable`! You are correct that in `cache-manager` there is not an easy way to do this other than storing the Keyv modules and doing it individually. 

```js
import { Keyv } from 'keyv';
import KeyvRedis from '@keyv/redis';
import { KeyvCacheableMemory } from 'cacheable';
import { createCache } from 'cache-manager';

// Multiple stores
const memoryStore = new Keyv({ store: new KeyvCacheableMemory({ ttl: 60000, lruSize: 5000 }) });
const redisStore = new Keyv({ store: new KeyvRedis('redis://user:pass@localhost:6379') });
const cache = createCache({
  stores: [ memoryStore, redisStore ],
});

// to disconnect you would need to do:
await redisStore.disconnect();
```

You could use `cacheable` which is the more modern caching system that has disconnect built in. Here is an example of that:

```js
import KeyvRedis from '@keyv/redis';
import { Cacheable, KeyvCacheableMemory } from 'cacheable';

const primary = new KeyvCacheableMemory({ ttl: 60000, lruSize: 5000 });
const secondary = new KeyvRedis('redis://user:pass@localhost:6379');
const cache = new Cacheable({ primary, secondary });

// to disconnect which will handle both primary and secondary stores
await cache.disconnect();
```

Hope this helps!

**Comment by TimothyIp** [comment]
@jaredwray Thanks for taking the time for answering this. I appreciate it a lot! 

Would it be a welcome addition to add a `disconnect()` method to `cache-manager`? It would just run disconnect across the set stores inside of it.

**Comment by jaredwray** [comment]
@TimothyIp - I will add it to the list but might not happen for a bit.

**Comment by TimothyIp** [comment]
@jaredwray  No worries, I can rip a PR for it. Just let me know if it looks good.

**Comment by jaredwray** [comment]
@TimothyIp - this should be released today once npm is finished with their maintenance.
