### ISSUE TITLE
@keyv/offline alternative

### ISSUE THREAD

**Issue by iiAku** [jaredwray/cacheable#915]
Hello,

I have been using `@keyv/offline` and I have seen it was deprecated in favor of cacheable.
However I am struggling to make cacheable work the same way it was working before.
If I understand way cacheable is in-memory as layer 1 by default.

However I want to achieve something slightly different.

I want to have redis as my primary store and getting "an offline" like response if for instance my store is not responding or something, but not in-memory, also I want this to be non blocking how to achieve this ?

```ts
import KeyvRedis from '@keyv/redis';
import {Cacheable} from 'cacheable';
import KeyvOffline from "@keyv/offline";

const inMemoryCached = async () => {
    //This will basically return the in-memory cache when redis is down
    const secondary = new KeyvRedis('redis://localhost:6379');
    const cache = new Cacheable( { secondary, nonBlocking: true} );
    await cache.set('foo', 'bar');
    const value = await cache.get('foo');
    console.log({inMemory: value});
}

const offline = async () => {
    //This should return undefined (and be non-blocking) if redis is down
    const primary = new KeyvRedis('redis://localhost:6379');
    const kv = new KeyvOffline(primary)
    await kv.set('bar', 'foo');
    const value = await kv.get('bar');
    console.log({offline: value});
}

const offlineCacheableWay = async () => {
    //This should return undefine if redis is down, but this is blocking
    const primary = new KeyvRedis('redis://localhost:6379');
    const cache = new Cacheable( { primary, nonBlocking: true} );
    await cache.set('foo2', 'bar2');
    const value = await cache.get('foo2');
    console.log({offlineCacheableWay: value});
}

const main = async () => Promise.all([inMemoryCached(), offline(), offlineCacheableWay()]);

main()


//output:
{
  inMemory: "bar",
}

```

What is the way to go to achieve that.
- If redis is UP cache and return value from redis
- If redis is DOWN (throwing or something else) return null as if value or cache is invalidated

Thanks for writing these amazing libraries and thanks for your time

**Comment by iiAku** [comment]
This is a way I found of doing it, but It's looks like hacky

```ts
import Keyv from 'keyv';
import KeyvRedis from '@keyv/redis';
import {CacheableMemory, KeyvCacheableMemory} from "cacheable";
import {createCache} from "cache-manager";

const main = async()=> {
    const kv =  new Keyv({store: new KeyvRedis('redis://llocalhost:6379'), ttl:10000, namespace:'test', useKeyPrefix: false})
    const cacheableMemory = new Keyv(new CacheableMemory({ ttl: 1, lruSize: 5000, checkInterval: 1}))

    kv.on('error',  (err) => {})

    const cache = createCache({
        stores: [ kv, cacheableMemory],
        nonBlocking: true,
    })

    await cache.set('foo', 'bar');
    const value = await cache.get('foo');
    console.log({value}); //{ value: 'bar' }
}

main()
```

**Comment by jaredwray** [comment]
@iiAku - `cacheable` was built to have true layer 1 / layer 2 system and we believe is a better way of handling caching in production because you will want a returned value if your secondary store is offline (in our opinion). With that said, We understand that this might not be the use case you are looking for. 

The example with `cache-manager` is probably your best alternative as it was designed less around primary and secondary but to have many stores on the backend.
