### ISSUE TITLE
[cache-manager] Add an option to update all layers/stores on refresh

### ISSUE THREAD

**Issue by meteorlxy** [jaredwray/cacheable#916]
**Is your feature request related to a problem? Please describe.**

For example, there is a 2-layer cache:

```
Layer 1 -> ttl=1d
Layer 2 -> ttl=2d
```

Both of them have `refreshThreshold=1h`

After 23h, the Layer 1 will refresh according to refreshThreshold.

However, per the current implementation, only `stores.slice(0, i + 1)` (only Layer 1 in this case) will be updated, while the Layer 2 still have stale data:

https://github.com/jaredwray/cacheable/blob/64f4341886f607d50465326e8e6aef48b5e15219/packages/cache-manager/src/index.ts#L206-L215

If the Layer 1 somehow crashed between 1d and 2d, the cache will fallback to Layer 2 with stale data, which is not ideal.

**Describe the solution you'd like**

Provide a new option like `refreshAllStores` to update all layers on refresh.

**Comment by jaredwray** [comment]
@meteorlxy - We will get this merged and published in the next 5-7 days! 🎉
