### ISSUE TITLE
TTL is reset when cache is saved/loaded

### ISSUE THREAD

**Issue by chris48s** [jaredwray/cacheable#926]
**Describe the bug**

When a cache is saved/loaded from disk, the expiry for every value is re-set on load.

**How To Reproduce (best to provide workable code or tests!)**

Here's a a minimal example that reproduces the issue:

```js
import { FlatCache } from 'flat-cache'
import assert from "node:assert";

const sleep = async (ms) => new Promise(resolve => setTimeout(resolve, ms));

const cache = new FlatCache({ ttl: '2000' });
cache.set('foo', 'bar');
cache.save();
await sleep(4000);
cache.load();
assert.equal(cache.get('foo'), undefined);
```

This assertion will pass if you remove the lines `cache.save()` and `cache.load()` but fails with them in.

**Everything Else**

This happens because expiry timestamp is re-set at the point a value is saved to the cache, and loading a saved cache from disk calls `.set()` for each key/value in the file.

The upshot of this is that TTL works for long-running applications like a web server that boots up and then stays active listening for incoming requests and holds the cache in memory the whole time. However for short-lived processes like a CLI tool that loads the cache, runs for a few seconds, saves the cache back to disk and then exits until next time it is invoked, TTL is essentially completely ignored.

I find this behaviour unexpected.

My suggestion for how to solve this would be that the expiry timestamp for each cache entry should be written to the cache file when it is persisted and then those expiry timestamps should be read and set when the cache is loaded back into memory instead of re-calculating the expiry from the point where the cache entries are loaded back into the cache.

**Comment by jaredwray** [comment]
@chris48s - thanks for finding this and I will look at this over the weekend to see if we can do a fix asap.

**Comment by jaredwray** [comment]
@chris48s - thanks for your patience. We have a plan now and will be extending the cache to work better and store the expires so it is not lost. Should be done in the next week or two.

**Comment by jaredwray** [comment]
@chris48s - this is now getting fixed and should be live in the next couple weeks.

**Comment by jaredwray** [comment]
#933

**Comment by jaredwray** [comment]
@chris48s - this should be live in the next couple days or so. NPM is having issues so waiting for it to resolve 🎉
