### ISSUE TITLE
Reading TTL

### ISSUE THREAD

**Issue by Janhouse** [jaredwray/cacheable#930]
In older version of cache-manager I could access `.store.ttl(...)` to read the TTL of the cached entry, but I am unable to find how to achieve that in current version. Is this not possible anymore?

**Comment by jaredwray** [comment]
Hi @Janhouse 👋 - that is correct that once we switched to Keyv as the primary backend this was removed. Were you trying to read when it would expire?

**Comment by Janhouse** [comment]
Seems like Keyv allows to set raw mode for get(), which then also returns the ttl timestamp.
It also offers to access iterator for storage which is missing in current version of cache-manager.
I will try using Keyv directly and see if it works for me.

**Comment by jaredwray** [comment]
I think it makes sense to add it back in if you are after the expires. Thoughts?

**Comment by jaredwray** [comment]
@Janhouse - just published `ttl()` with `cache-manager@6.3.1` 🍻

**Comment by Janhouse** [comment]
@jaredwray great! While we are on topic of bringing back features, could you please consider exposing iterator of the store, or add some other way of getting all the keys in the store?
Testing with keyv postrge backend I noticed that iterator gets direct access and keys are prepended with `keyv:` as they are stored in the actual database. So, getting all keys without that prefix would be great.

**Comment by jaredwray** [comment]
@Janhouse - you can set useKeyPrefix to false in Keyv to make it not use prefixing. 

https://github.com/jaredwray/keyv/tree/main/packages/keyv#usekeyprefix
