### ISSUE TITLE
Confusion over which library to use - overlapping solutions?

### ISSUE THREAD

**Issue by gkatsanos** [jaredwray/cacheable#963]
Hello, first of all thank you for all the amazing work you've put into caching. 
I started going through the cacheable, cache-manager, then jumped over to @keyv documentations but I admit I'm still very unclear on what one needs to use and where.

To narrow it down: I want to experiment with simple in-memory caching for a simple Node/Express 4 API application in order to reduce calls to an external API. Ultimately we might switch to another strategy like Redis, or sqlite. 

So I guess I need a solution that I can just drop-in replace the adapter/backend as easy and as seamlessly as possible.

Having multi-tier caching would also be ideal (aka use in memory + redis combined). 

So looking at the documentation, it seems:

```js
import { Cacheable } from 'cacheable';
import KeyvRedis from '@keyv/redis';

const secondary = new KeyvRedis('redis://user:pass@localhost:6379');
const cache = new Cacheable({secondary});
```

is what I'd need to use? 

So I guess the advantage of cacheable over pure @keyv  is the unified API which allows me to cache things without needing to specify which adapter handles it in the background, right?

Sorry for the long question! not really an issue, even though I'd say a more explicit usage table for each solution would help tremendously!

**Comment by jaredwray** [comment]
@gkatsanos - thanks for the note and if you are looking for a caching solution I would recommend to use Cacheable over Keyv. The reason is that Keyv's primary focus is to be a storage adapter which is why we made `Cacheable` as we saw people using it for caching. What is great about Cacheable is that by default it comes with an in-memory driver that is optimized:

```js
import { Cacheable } from `cacheable`;

const cache = new Cacheable();
```

This will give you an in-memory cache that is very scalable. If you want to configure the in-memory you can do the following:

```js
import { Cacheable, CacheableMemory } from `cacheable`;

const options = {
  ttl: '1h', // 1 hour
  useClones: true, // use clones for the values (default is true)
  lruSize: 1000, // the size of the LRU cache (default is 0 which is unlimited)
}
const primary = new CacheableMemory(options);
const cache = new Cacheable({primary});
```

https://cacheable.org/docs/cacheable/#cacheablememory---in-memory-cache

Then later on you can expand this like the example you have to have a layer 1 and layer 2 cache like so:

```js
import { Cacheable, CacheableMemory } from `cacheable`;
import KeyvRedis from `@keyv/redis`;

const options = {
  ttl: '1h', // 1 hour
  useClones: true, // use clones for the values (default is true)
  lruSize: 1000, // the size of the LRU cache (default is 0 which is unlimited)
}
const primary = new CacheableMemory(options);
const secondary = new KeyvRedis('redis://user:pass@localhost:6379');
const cache = new Cacheable({primary, secondary});
```

Hope this helps.

**Comment by gkatsanos** [comment]
Thank you Jared! I really appreciate the detailed response.
Sorry for the unrelated / irrelevant question: Would caching unresolved Promises be possible? (I assume not) - seems they cant be resolved after getting the values back from cache.

**Comment by jaredwray** [comment]
I dont think you can do an unresolved promise or what that use case would be used for. One thing to think about is the `wrap()` function. Check that out: https://cacheable.org/docs/cacheable/#wrap--memoization-for-sync-and-async-functions
